theme: jekyll-theme-slate
title: Health Buddy Reports
description: A collection of health reports and summaries
baseurl: "/health_buddy_reports_new"  # Add this line
url: "https://ypff.github.io"          # Optional, for clarity
